/**
 * Copy the runtime and the model into the extension folder.
 *
 * Neither is committed: onnxruntime is 14 MB of third-party build output and the model is
 * generated by the training pipeline. Both are reproducible, so they are fetched here
 * instead, and `vendor/` plus `model/` are ignored by git.
 *
 *   npm run vendor
 */

import { copyFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const extension = resolve(here, "..");
const repository = resolve(extension, "..", "..");

const RUNTIME = [
  "ort.wasm.min.mjs",
  "ort-wasm-simd-threaded.mjs",
  "ort-wasm-simd-threaded.wasm",
];

const MODELS = [
  ["models/tagger.int8.onnx", "model/tagger.onnx"],
  ["models/tagger.int8.json", "model/tagger.json"],
  // Built by scripts/build_bundle.py: the words the training text was unanimous about.
  ["packages/core/duzelt/data/lexicon.tsv.gz", "model/lexicon.tsv.gz"],
];

function copy(from, to) {
  mkdirSync(dirname(to), { recursive: true });
  copyFileSync(from, to);
  return to;
}

let copied = 0;

for (const name of RUNTIME) {
  const from = join(extension, "node_modules", "onnxruntime-web", "dist", name);
  if (!existsSync(from)) {
    console.error(`missing ${name}; run npm install first`);
    process.exit(1);
  }
  copy(from, join(extension, "vendor", name));
  copied += 1;
}

let model = false;
for (const [from, to] of MODELS) {
  const source = join(repository, from);
  if (existsSync(source)) {
    copy(source, join(extension, to));
    model = true;
    copied += 1;
  }
}

console.log(`${copied} files copied`);
if (!model) {
  console.log(
    "no model found: run scripts/export_onnx.py and scripts/quantize_onnx.py in the " +
      "repository root, or leave it out and the extension will use the service instead.",
  );
}
